### ISSUE TITLE
Case 10: Robot not spin.

### ISSUE THREAD

**Issue by vbirjuko** [ukmars/ukmarsbot-examples#2]
https://github.com/ukmars/ukmarsbot-examples/blob/7b85580ed3fe7606d2f2cad2e60d4e4672ad38e2/basic-pwm/basic-pwm.ino#L139
Robot not spin.
Must be 
setMotorPWM(127, -127);        // spin right 50%

**Comment by micromouseonline** [comment]
If you look through the documents, you will see that the actual direction of the motors depends on how they are wired up. that is one of the things that you need tcheck when building the robot.  You can either change the code or swap the motor leads around. 

Here though, you are correct and the value should be negative to match the other cases.

Thank you.

**Comment by micromouseonline** [comment]
Fixed.
